### ISSUE TITLE
Bump bounds on win32? 

### ISSUE THREAD

**Issue by gbaz** [haskell/HTTP#115]
The new ghc ships with Win32 2.6.10.

It would be good to bump the bounds on HTTP for the HP release. In testing this, we also ran into some bounds on conduit it would be good to bump (in the test suite). I see there are actually even far newer versions of Win32 out -- up to 2.7.0.0. So ideally, if it was safe, it would be good to advance things all the way there.

If this can be done just with revisions and without a new release, I'd be fine with that, but a new release would be fine too...

**Comment by gbaz** [comment]
Note: there appears to be at least one breaking change for this package between different Win32 packages:

    Win32-2.6.1.0: regQueryValue :: HKEY -> String -> IO String
    Win32-2.5.4.1: regQueryValue :: HKEY -> Maybe String -> IO String

**Comment by hsenag** [comment]
Thanks, I'll take a look. I was watching 'packdeps' but looks like it doesn't report dependencies on other platforms or in the test suite, so I'll need to pay closer attention.

**Comment by hsenag** [comment]
I've bumped to support Win32 2.6, and the latest version of other deps (time, conduit, conduit-extra), and uploaded 4000.3.11.

Still to do is check Win32 2.7, I haven't installed a recent enough GHC on Windows for that yet.
