### ISSUE TITLE
Extract Code that Creates http Headers and Body

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/HTTP#125]
The HTTP package seems to be for creating the http **client**. I have seen the HTTP package used to construct the http response on the [server side](http://hackage.haskell.org/package/http-server) as well.

With the http needing to created on the client and server side it would seem to be a good idea to extract the ability to create http into it's own or sub package.

What do you think?

**Comment by hsenag** [comment]
Does http://hackage.haskell.org/package/http-types meet the requirements?

In general I'm not sure that `HTTP` is a good choice for new projects, it's quite old and crufty and doesn't support HTTPS. Its advantages are really incumbency, and that it only has a small number of dependencies.

**Comment by BebeSparkelSparkel** [comment]
@hsenag Thanks for pointing to that package. I think it will work but the http seems more thought out.
