### ISSUE TITLE
Support for GHC-9.0

### ISSUE THREAD

**Issue by phadej** [haskell/HTTP#134]
Looks like code changes are required:

```
Network/TCP.hs:92:30: error:
    Operator applied to too few arguments: !
   |
92 |  = MkConn { connSock      :: ! Socket
   |                      
```

**Comment by DeX77** [comment]
This breaks pandoc.

**Comment by hsenag** [comment]
@DeX77  You mean you need this fix for pandoc? Or this fix actually breaks pandoc somehow?

**Comment by DeX77** [comment]
@hsenag I meant I need this fixed to build pandoc with GHC 9.x, as pandoc requires HTTP.

**Comment by hsenag** [comment]
> @hsenag I meant I need this fixed to build pandoc with GHC 9.x, as pandoc requires HTTP.

OK - sorry for the delay, I've merged the submitted PR now and will push a new release shortly. I had seen the original discussion about the fix being blocked on other packages and missed that it became unblocked.

**Comment by hsenag** [comment]
4000.3.16 uploaded to hackage with the fix for this. Thanks @phadej !
