### ISSUE TITLE
simpleHTTP raises exception on "https"

### ISSUE THREAD

**Issue by vlatkoB** [haskell/HTTP#77]
Hello,

In documentation for `simpleHTTP` it is not mentioned that it raises IO exception if url is "https" (through failHTTPS).
It should be mentioned in docs, or even better, it should catch it and return `Left` (maybe ErrorMisc).

Best regards,
vlatko

**Comment by oherrala** [comment]
With pull request #103 the behaviour changes from exception into ```Left``` result:

```
λ> import Network.HTTP
λ> Network.HTTP.simpleHTTP (getRequest "https://haskell.org")
Left (ErrorMisc "user error (https not supported)")
```
