### ISSUE TITLE
Network.HTTP.Proxy.fetchProxy fails on Windows 7

### ISSUE THREAD

**Issue by Prillan** [haskell/HTTP#82]
My proxy settings are set to the following in Windows:
    
    Type   Proxy address to use  Port      
    HTTP   127.0.0.1             3213
    HTTPS  127.0.0.1             3213
    FTP    <empty>               <empty>
    SOCKS  <empty>               <empty>

Which leads to the following error using `cabal`

    Invalid http proxy uri: "http=127.0.0.1:3213;https=127.0.0.1:3213"
    proxy uri must be http with a hostname
    ignoring http proxy, trying a direct connection

The registry stores the proxy setting in the format seen above. From what I can see in the source code, no effort is made to actually parse this string which then always returns an invalid string.

**Comment by hsenag** [comment]
The fix should be on hackage in version 4000.2.20, please reopen this if there are any problems.
