### ISSUE TITLE
Remove dep on old-time?

### ISSUE THREAD

**Issue by gbaz** [haskell/HTTP#91]
Is it possible to stop relying on old-time in HTTP? It would be nice to stop doing so to start flushing the old-* libraries out of the core ecosystem.

**Comment by hsenag** [comment]
Sounds sensible. Is there a minimum sensible version of GHC for that? Currently HTTP supports GHC 7.0+, but I'm happy to bump that up a bit for a good reason.

**Comment by gbaz** [comment]
It looks like GHC 7.0.1 shipped with time 1.2.0.3. (http://downloads.haskell.org/~ghc/7.0.1/docs/html/libraries/time-1.2.0.3/Data-Time.html) So I'd imagine that any code ported from old-time to time could use anything already available there -- I think it was pretty stable by that point already?

**Comment by hsenag** [comment]
OK, so looks like this should be pretty simple - there's one use of `System.Time` in [Network.Browser](https://github.com/haskell/HTTP/blob/master/Network/Browser.hs#L152), and I think it can simply be replaced by [UTCTime](https://hackage.haskell.org/package/time-1.5.0.1/docs/Data-Time-Clock.html#t:UTCTime).

It will require a major version bump as it's part of an exposed type (`BrowserEvent`), though I'm not sure if anyone actually uses this.

**Comment by hsenag** [comment]
Resolved in [HTTP 4000.3.0](http://hackage.haskell.org/package/HTTP-4000.3.0)
