### ISSUE TITLE
GHC 8.0.1 support

### ISSUE THREAD

**Issue by peti** [haskell/HTTP#99]
Currently, GHC 8.0.1-rc2 cannot compile HTTP: http://hydra.cryp.to/build/1606798/nixlog/1/raw. It would be great to get an update on Hackage that remedies this issue.

**Comment by hvr** [comment]
Seems fixed via http://hackage.haskell.org/package/HTTP-4000.3.3, can you confirm?

I was finally able to build cabal-install from Git with GHC 8

**Comment by peti** [comment]
Yes, HTTP-4000.3.3 compiles fine. Thank you very much.
